#!/bin/bash

case "$1" in
    background_job)
        python -m rep0st.background_job
        ;;
    site)
        python -m web.site
        ;;
    test)
        python test.py
        ;;
    tags)
        python -m rep0st.tags
        ;;
    *)
        echo $"Usage: $0 {background_job|site|test|tags}"
        exit 1
esac