#!/bin/bash
set -eo pipefail

if health=`curl -fsSL "http://127.0.0.1:9200/_cat/health?h=status"`; then
	health="$(echo "$health" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" # trim whitespace (otherwise we'll have "green ")
	if [ "$health" = 'green' ]; then
		exit 0
	fi
        if [ "$health" = 'yellow' ]; then
                # We also consider yellow good. We run only one instance in the cluster and elasticsearch doesn't like that.
                exit 0
        fi
	echo >&2 "unexpected health status: $health"
fi

exit 1
