services:
  pg01:
    build:
      context: ./
      dockerfile: postgresql.Dockerfile
    restart: no
    environment:
      POSTGRESQL_USERNAME: rep0st
      POSTGRESQL_PASSWORD: pw
      POSTGRESQL_DATABASE: rep0st
      POSTGRESQL_POSTGRES_PASSWORD: pw
    ports:
      - 5432:5432
    shm_size: 32768mb
    volumes:
      - pg01data:/bitnami/postgresql
      - ./postgres_performance.conf:/opt/bitnami/postgresql/conf/conf.d/postgres_performance.conf

volumes:
  pg01data:
    driver: local
