services:
  update_posts:
    build:
      context: ../
      dockerfile: deployment/rep0st.Dockerfile
    restart: always
    command:
      - rep0st.job.update_posts_job
      - --webserver_bind_hostname=0.0.0.0
      - --webserver_bind_port=5000
      - --pr0gramm_api_user_file=/run/secrets/pr0gramm_user
      - --pr0gramm_api_password_file=/run/secrets/pr0gramm_password
      - --rep0st_update_posts_end_id=500
      - --rep0st_database_uri=postgresql+psycopg2://rep0st:pw@pg01:5432/rep0st
      - --rep0st_update_all_posts_job_schedule=*/5 * * * *
      - --rep0st_media_path=/media/
    depends_on:
      - pg01
    ports:
      - 5001:5000
    volumes:
      - media:/media
    secrets:
      - pr0gramm_user
      - pr0gramm_password

  update_features:
    build:
      context: ../
      dockerfile: deployment/rep0st.Dockerfile
    restart: always
    command:
      - rep0st.job.update_features_job
      - --webserver_bind_hostname=0.0.0.0
      - --webserver_bind_port=5000
      - --rep0st_database_uri=postgresql+psycopg2://rep0st:pw@pg01:5432/rep0st
      - --rep0st_media_path=/media/
      - --rep0st_update_features_post_type=IMAGE
    depends_on:
      - pg01
    ports:
      - 5002:5000
    volumes:
      - media:/media:ro

  update_video_features:
    build:
      context: ../
      dockerfile: deployment/rep0st.Dockerfile
    restart: always
    command:
      - rep0st.job.update_features_job
      - --webserver_bind_hostname=0.0.0.0
      - --webserver_bind_port=5000
      - --rep0st_database_uri=postgresql+psycopg2://rep0st:pw@pg01:5432/rep0st
      - --rep0st_media_path=/media/
      - --rep0st_update_features_post_type=VIDEO
    depends_on:
      - pg01
    ports:
      - 5003:5000
    volumes:
      - media:/media:ro

  web:
    build:
      context: ../
      dockerfile: deployment/rep0st.Dockerfile
    restart: always
    command:
      - rep0st.web
      - --webserver_bind_hostname=0.0.0.0
      - --webserver_bind_port=5000
      - --rep0st_database_uri=postgresql+psycopg2://rep0st:pw@pg01:5432/rep0st
    depends_on:
      - pg01
    ports:
      - 5000:5000

secrets:
  pr0gramm_user:
    file: ../secrets/pr0gramm_user.txt
  pr0gramm_password:
    file: ../secrets/pr0gramm_password.txt

volumes:
  media:
    driver: local
