services:
  postgresql:
    build:
      context: ./
      dockerfile: postgresql.Dockerfile
    image: docker-registry.internal.serv0r.xyz/rep0st-postgresql:${TAG:-latest}

  app:
    build:
      context: ../
      dockerfile: deployment/rep0st.Dockerfile
    image: docker-registry.internal.serv0r.xyz/rep0st-app:${TAG:-latest}
