version: '3.9'

services:
  mariadb:
    build:
      context: ./
      dockerfile: mariadb.Dockerfile
    image: docker-registry.internal.serv0r.xyz/rep0st-mariadb

  elasticsearch:
    build:
      context: ./
      dockerfile: elastiksearch.Dockerfile
    image: docker-registry.internal.serv0r.xyz/rep0st-elasticsearch

  app:
    build:
      context: ../
      dockerfile: deployment/rep0st.Dockerfile
    image: docker-registry.internal.serv0r.xyz/rep0st-app
